# Debian/Pop!_OS specific package names and settings

os_cli_dependencies:
  - build-essential
  - curl
  - wget
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - wl-clipboard
  - nfs-common

os_dev_packages:
  - docker.io

os_other_packages:
  - steam-installer
  - fonts-powerline
