# Shared, cross-platform variables for both Pop!_OS and Fedora KDE

# Target User & Base Paths
target_user: "boris"
target_home: "{{ ansible_user_dir | default('/home/' + target_user) }}"
nas_backup_base_dir: "{{ target_home }}/Backup"

common_cli_packages:
  - git
  - jq
  - bat
  - direnv
  - micro
  - timeshift
  - keychain
  - borgbackup
  - age
  - stow
  - flatpak
  - syncthing
  - ark
  - zip
  - unzip


common_dev_packages:
  - zsh
  - zsh-autosuggestions

common_other_packages:
  - firefox
  - discord
  - gamescope
  - plasma-systemmonitor
  - gwenview

flatpak_packages:
  - com.logseq.Logseq
  - org.prismlauncher.PrismLauncher
  - io.kinvolk.Headlamp
  - md.obsidian.Obsidian
  - org.kde.haruna

homebrew_packages:
  - kubectl
  - bitwarden-cli

purged_os_packages:
  - libreoffice*
  - kmail*
  - kontact*
  - korganizer*
  - dragon

# BorgBackup Variables
borg_repository: "{{ nas_backup_base_dir }}/borg-repo"
borg_backup_sources:
  - "/media/boris/DataDrive/Documents"
  - "/media/boris/DataDrive/all Nata"
  - "/media/boris/DataDrive/Music"
  - "/media/boris/DataDrive/Photos"
  - "/media/boris/DataDrive/Resources"
  - "/media/boris/DataDrive/Roms"
  - "/media/boris/DataDrive/Video"

# Secondary HDD Mount Variables
hdd_uuid: "93e35c87-80a1-497c-85d0-a16b9448ea10"
hdd_mount_point: "/media/boris/DataDrive"
hdd_fstype: "auto"
hdd_mount_opts: "nosuid,nodev,nofail,x-gvfs-show"

# Secrets & Dotfiles Backup Variables (age + Bitwarden)
age_public_key: "age15njthcvfc2jsdt37st0patwqfz3tlv7tz683wssmz7jfd5pwceqs85az0k"
secrets_backup_dir: "{{ nas_backup_base_dir }}/secrets_backups"
secrets_backup_max_keep: 5
bitwarden_item_name: "os_setup_secrets_key"
secrets_backup_targets:
  - ".ssh"
  - ".kube"
  - ".gitconfig"
  - ".gnupg"
  - ".zsh_history"
  - "ansible/vars/secrets.yml"
secrets_backup_required_targets:
  - "ansible/vars/secrets.yml"
  - ".ssh"


