# Shared, cross-platform variables for both Pop!_OS and Fedora KDE

common_cli_packages:
  - git
  - jq
  - bat
  - direnv
  - micro
  - timeshift
  - keychain
  - borgbackup
  - stow
  - flatpak

common_dev_packages:
  - zsh
  - zsh-autosuggestions

common_other_packages:
  - firefox
  - vlc
  - discord
  - gamescope
  - plasma-systemmonitor
  - gwenview

flatpak_packages:
  - com.logseq.Logseq
  - org.prismlauncher.PrismLauncher
  - io.kinvolk.Headlamp

homebrew_packages:
  - kubectl

purged_os_packages:
  - libreoffice*
  - kmail*
  - kontact*
  - korganizer*
  - dragon

# BorgBackup Variables
borg_repository: "/home/boris/Backup/borg-repo"
borg_backup_sources:
  - "/media/boris/DataDrive/Documents"
  - "/media/boris/DataDrive/all Nata"
  - "/media/boris/DataDrive/Music"
  - "/media/boris/DataDrive/Photos"
  - "/media/boris/DataDrive/Resources"
  - "/media/boris/DataDrive/Roms"
  - "/media/boris/DataDrive/Video"

# Secondary HDD Mount Variables
hdd_uuid: "93e35c87-80a1-497c-85d0-a16b9448ea10"
hdd_mount_point: "/media/boris/DataDrive"
hdd_fstype: "auto"
hdd_mount_opts: "nosuid,nodev,nofail,x-gvfs-show"
