# RedHat/Fedora specific package names and settings

os_cli_dependencies:
  - gcc
  - gcc-c++
  - make
  - curl
  - wget
  - util-linux-user
  - procps-ng
  - wl-clipboard
  - xcb-util-cursor
  - nfs-utils

# OS-Specific NAS Mounts (NFS for Fedora)
nas_mounts:
  - { path: "mnt/SharedLand", src: "homecloud.local:/volume1/SharedLand", fstype: "nfs", opts: "noauto,x-systemd.automount,x-systemd.idle-timeout=600,x-systemd.device-timeout=5,timeo=14,_netdev" }

os_dev_packages:
  - moby-engine

os_other_packages:
  - steam
  - powerline-fonts
  - mesa-va-drivers-freeworld
  - kde-partitionmanager
